// <auto-generated>
// Code generated by LUISGen LiriStock.json -cs Luis.LiriStockModel -o 
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;

namespace Microsoft.BotBuilderSamples
{
    public partial class LiriStockModel: IRecognizerConvert
    {
        [JsonProperty("text")]
        public string Text;

        [JsonProperty("alteredText")]
        public string AlteredText;

        public enum Intent {
            BookFlight,
            GetWeather,
            Cancel,             
            None, 
            TFGStock
        };

        [JsonProperty("intents")]
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] Color;

            public string[] Garment;

            public string[] Brand;

            public string[] Size;

            // Built-in entities
            public DateTimeSpec[] datetime;

            // Lists
            public string[][] Airport;

            // Composites
            public class _InstanceFrom
            {
                public InstanceData[] Branch;
            }

            public class FromClass
            {
                public string[][] Branch;
                [JsonProperty("$instance")]
                public _InstanceFrom _instance;
            }

            public FromClass[] From;

            public class _InstanceTo
            {
                public InstanceData[] Branch;
            }

            public ToClass[] To;

            public class ToClass
            {
                public string[][] Branch;
                [JsonProperty("$instance")]
                public _InstanceTo _instance;
            }

            // Instance
            public class _Instance
            {
                public InstanceData[] Airport;
                public InstanceData[] Branch;
                public InstanceData[] Color;
                public InstanceData[] From;
                public InstanceData[] Garment;
                public InstanceData[] To;
                public InstanceData[] Brand;
                public InstanceData[] datetime;
                public InstanceData[] Size;
            }

            [JsonProperty("$instance")]
            public _Instance _instance;
        }

        [JsonProperty("entities")]
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        /// <summary>
        /// Convert recognizer result.
        /// </summary>
        /// <param name="result">Result to convert.</param>
        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<LiriStockModel>(JsonConvert.SerializeObject(result, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        /// <summary>
        /// Tops the intent.
        /// </summary>
        /// <returns></returns>
        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
